# Generated by Django 4.0.10 on 2024-03-21 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_currency_currencyrate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Валюта'},
        ),
    ]
